Error occurred: fetch_and_save_block_data() takes 1 positional argument but 2 were given
Error occurred: fetch_and_save_block_data() takes 1 positional argument but 2 were given
File 'C:/Users/lmhmo/indexer/Decrypted_files/584389_1.json' does not exist.
Error occurred: fetch_and_save_block_data() takes 1 positional argument but 2 were given
Error occurred: fetch_and_save_block_data() takes 1 positional argument but 2 were given
File 'C:/Users/lmhmo/indexer/Decrypted_files/584389_1.json' does not exist.
File 'C:/Users/lmhmo/indexer/blocks/5904854.json' does not exist.
File 'C:/Users/lmhmo/indexer/blocks/5905784.json' does not exist.
File 'C:/Users/lmhmo/indexer/Decrypted_files/584389_1.json' does not exist.
File 'C:/Users/lmhmo/indexer/Decrypted_files/584389.json' does not exist.
File 'C:/Users/lmhmo/indexer/Decrypted_files/5846136.json' does not exist.
Error occurred: fetch_and_save_block_data() takes 1 positional argument but 2 were given
Error occurred: fetch_and_save_block_data() takes 1 positional argument but 2 were given
Error occurred: fetch_and_save_block_data() takes 1 positional argument but 2 were given
File 'C:/Users/lmhmo/Indexer_Project/indexer_project/blocks/6039131.json' does not exist.
Error occurred: HTTPConnectionPool(host='116.202.143.93', port=1317): Max retries exceeded with url: /cosmos/base/tendermint/v1beta1/blocks/5929489 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028E38A7BB30>: Failed to establish a new connection: [WinError 10065] A socket operation was attempted to an unreachable host'))
File 'C:/Users/lmhmo/Indexer_Project/indexer_project/blocks/59251581.json' does not exist.
File 'C:/Users/lmhmo/Indexer_Project/indexer_project/blocks/59251581.json' does not exist.
File 'C:/Users/lmhmo/Indexer_Project/indexer_project/blocks/59251581.json' does not exist.
Error occurred: fetch_and_save_block_data() takes 1 positional argument but 2 were given
